-- FiinGroupApp project-management business store.
-- Ported from the trusted Jarvis PM schema/migrations.
-- No seed data. Apply only to FiinGroupApp.ProjectManagement.

CREATE TABLE IF NOT EXISTS pm_project (
  id INT NOT NULL AUTO_INCREMENT,
  id_project INT DEFAULT NULL,
  pm VARCHAR(50) NOT NULL,
  customer VARCHAR(255) NOT NULL,
  project_code VARCHAR(100) DEFAULT NULL,
  annex_no VARCHAR(100) DEFAULT NULL,
  annex_name VARCHAR(255) DEFAULT NULL,
  contract_type TINYINT NOT NULL DEFAULT 1,
  product_id BIGINT DEFAULT NULL,
  project_option TINYINT DEFAULT NULL,
  project_type TINYINT DEFAULT NULL,
  amount DECIMAL(18,0) DEFAULT 0,
  percent_budget DECIMAL(5,2) DEFAULT 0.00,
  budget DECIMAL(18,0) DEFAULT 0,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  sign_date DATE DEFAULT NULL,
  acceptance_date DATE DEFAULT NULL,
  warranty_months INT DEFAULT NULL,
  warranty_end_date DATE DEFAULT NULL,
  maintenance_percent DECIMAL(5,2) DEFAULT NULL,
  next_action_date DATE DEFAULT NULL,
  is_tracking TINYINT NOT NULL DEFAULT 1,
  remarks TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  comm_percent DECIMAL(5,2) DEFAULT 0.00,
  comm_amount DECIMAL(18,0) DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_id_project (id_project),
  KEY idx_pm_project_product (product_id),
  KEY idx_pm_project_option (project_option),
  KEY idx_pm_project_type (project_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_project_task (
  id INT NOT NULL AUTO_INCREMENT,
  id_project INT NOT NULL,
  parent_id INT DEFAULT NULL,
  task_code VARCHAR(50) NOT NULL,
  task_name VARCHAR(255) NOT NULL,
  description MEDIUMTEXT DEFAULT NULL,
  product VARCHAR(500) DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  actual_start DATE DEFAULT NULL,
  actual_end DATE DEFAULT NULL,
  duration INT DEFAULT 0,
  progress DECIMAL(5,2) DEFAULT 0.00,
  plan DECIMAL(5,2) DEFAULT 0.00,
  priority TINYINT DEFAULT 2,
  task_type TINYINT DEFAULT 1,
  status TINYINT DEFAULT 0,
  sort_order INT DEFAULT 0,
  effort DECIMAL(8,2) DEFAULT NULL,
  pj_id BIGINT DEFAULT NULL,
  issue_id INT DEFAULT NULL,
  agile_sprint_id BIGINT DEFAULT NULL,
  is_critical TINYINT NOT NULL DEFAULT 0,
  nghiep_vu VARCHAR(255) DEFAULT NULL,
  muc_code VARCHAR(100) DEFAULT NULL,
  phase VARCHAR(100) DEFAULT NULL,
  dept_role VARCHAR(255) DEFAULT NULL,
  source_system VARCHAR(30) DEFAULT NULL,
  source_collection VARCHAR(191) DEFAULT NULL,
  source_project_id VARCHAR(191) DEFAULT NULL,
  source_id VARCHAR(191) DEFAULT NULL,
  source_revision INT DEFAULT NULL,
  source_url TEXT DEFAULT NULL,
  source_payload MEDIUMTEXT DEFAULT NULL,
  generated_fields JSON DEFAULT NULL,
  source_synced_at DATETIME DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_project (id_project),
  KEY idx_parent (parent_id),
  KEY idx_status (status),
  KEY idx_dates (start_date, end_date),
  KEY idx_created_by (created_by),
  KEY idx_source_project (source_system, source_collection, source_project_id),
  UNIQUE KEY uk_task_external_source (source_system, source_collection, source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_task_assignee (
  id INT NOT NULL AUTO_INCREMENT,
  task_id INT NOT NULL,
  assignee VARCHAR(50) NOT NULL,
  role TINYINT DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_assignee (task_id, assignee),
  KEY idx_assignee (assignee)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_task_dependency (
  id INT NOT NULL AUTO_INCREMENT,
  task_id INT NOT NULL,
  depends_on_id INT NOT NULL,
  dependency_type TINYINT DEFAULT 1,
  lag_days INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_dependency (task_id, depends_on_id),
  KEY idx_task (task_id),
  KEY idx_depends (depends_on_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_task_log (
  id INT NOT NULL AUTO_INCREMENT,
  task_id INT NOT NULL,
  updated_by VARCHAR(50) NOT NULL,
  field_name VARCHAR(50) NOT NULL,
  old_value TEXT DEFAULT NULL,
  new_value TEXT DEFAULT NULL,
  note TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_task (task_id),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_task_plan (
  id INT NOT NULL AUTO_INCREMENT,
  year INT NOT NULL,
  month INT NOT NULL,
  week INT NOT NULL,
  section_type TINYINT NOT NULL DEFAULT 2,
  entry_type TINYINT NOT NULL DEFAULT 0,
  customer VARCHAR(100) DEFAULT NULL,
  id_project INT DEFAULT NULL,
  task_desc TEXT NOT NULL,
  from_date DATE DEFAULT NULL,
  to_date DATE DEFAULT NULL,
  current_progress DECIMAL(5,2) DEFAULT 0.00,
  plan_progress DECIMAL(5,2) DEFAULT 0.00,
  result_progress DECIMAL(5,2) DEFAULT NULL,
  result_notes TEXT DEFAULT NULL,
  resource VARCHAR(500) DEFAULT NULL,
  remarks VARCHAR(500) DEFAULT NULL,
  sort_order INT DEFAULT 0,
  source_plan_id INT DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  status TINYINT DEFAULT 1,
  PRIMARY KEY (id),
  KEY idx_year_week (year, week),
  KEY idx_section (section_type),
  KEY idx_project (id_project),
  KEY idx_created_by (created_by),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_project_summary (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pm VARCHAR(50) DEFAULT NULL,
  year INT DEFAULT NULL,
  customer VARCHAR(255) DEFAULT NULL,
  id_project INT NOT NULL,
  pj_id BIGINT DEFAULT NULL,
  annex_name VARCHAR(255) DEFAULT NULL,
  plan_percent DECIMAL(5,2) DEFAULT 0.00,
  actual_percent DECIMAL(5,2) DEFAULT 0.00,
  week INT DEFAULT NULL,
  section_type TINYINT NOT NULL DEFAULT 1,
  entry_type TINYINT NOT NULL DEFAULT 1,
  source_plan_id INT DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  resources VARCHAR(500) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  updated_by VARCHAR(50) DEFAULT NULL,
  status TINYINT DEFAULT 1,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_project_week_section (id_project, year, week, section_type),
  KEY idx_year_week (year, week),
  KEY idx_section_type (section_type),
  KEY idx_created_by (created_by),
  KEY idx_source_plan_id (source_plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
