-- FiinGroupApp PMBOK read model.
-- Derived from the trusted Jarvis PMBOK migrations.
-- No source data or TFS mapping is inserted by this migration.

CREATE TABLE IF NOT EXISTS pm_project_charter (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  business_case TEXT DEFAULT NULL,
  objectives TEXT DEFAULT NULL,
  in_scope TEXT DEFAULT NULL,
  out_scope TEXT DEFAULT NULL,
  deliverables TEXT DEFAULT NULL,
  assumptions TEXT DEFAULT NULL,
  constraints_txt TEXT DEFAULT NULL,
  high_risks TEXT DEFAULT NULL,
  sponsor VARCHAR(100) DEFAULT NULL,
  product_owner VARCHAR(100) DEFAULT NULL,
  approval_status TINYINT NOT NULL DEFAULT 0,
  approved_by VARCHAR(100) DEFAULT NULL,
  approved_at DATETIME DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(100) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_charter_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_project_stakeholder (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  stakeholder_type ENUM('INTERNAL','EXTERNAL') NOT NULL DEFAULT 'INTERNAL',
  member VARCHAR(100) DEFAULT NULL,
  partner_cd VARCHAR(100) DEFAULT NULL,
  partner_contact_id BIGINT DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  role VARCHAR(255) DEFAULT NULL,
  power VARCHAR(10) DEFAULT NULL,
  interest VARCHAR(10) DEFAULT NULL,
  expectation TEXT DEFAULT NULL,
  engagement_strategy TEXT DEFAULT NULL,
  owner VARCHAR(100) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(100) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_stk_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_project_resource (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  member VARCHAR(100) DEFAULT NULL,
  role VARCHAR(100) DEFAULT NULL,
  sub_team VARCHAR(100) DEFAULT NULL,
  effort DECIMAL(4,2) DEFAULT NULL,
  unit_rate DECIMAL(12,2) DEFAULT NULL,
  planned_mandays DECIMAL(8,2) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(100) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_res_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_project_raci (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  activity VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  raci_value CHAR(1) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_raci_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_project_risk (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  risk_code VARCHAR(20) DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  category VARCHAR(50) DEFAULT NULL,
  probability TINYINT DEFAULT NULL,
  impact TINYINT DEFAULT NULL,
  score INT AS (COALESCE(probability, 0) * COALESCE(impact, 0)) STORED,
  response TEXT DEFAULT NULL,
  owner VARCHAR(100) DEFAULT NULL,
  trigger_desc VARCHAR(500) DEFAULT NULL,
  review_date DATE DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(100) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_risk_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_cost_plan (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  item_name VARCHAR(255) DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  amount DECIMAL(18,0) DEFAULT NULL,
  is_contingency TINYINT NOT NULL DEFAULT 0,
  contingency_percent DECIMAL(5,2) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(100) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_costplan_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_quality_plan (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  criteria VARCHAR(255) DEFAULT NULL,
  applies_to VARCHAR(255) DEFAULT NULL,
  verify_method VARCHAR(255) DEFAULT NULL,
  acceptance_standard TEXT DEFAULT NULL,
  owner VARCHAR(100) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(100) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_qp_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_quality_dod (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  item_text VARCHAR(500) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_dod_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_communication_plan (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  activity VARCHAR(255) DEFAULT NULL,
  purpose VARCHAR(500) DEFAULT NULL,
  audience VARCHAR(255) DEFAULT NULL,
  frequency VARCHAR(100) DEFAULT NULL,
  channel VARCHAR(100) DEFAULT NULL,
  owner VARCHAR(100) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(100) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_comm_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pm_change_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pj_id BIGINT NOT NULL,
  cr_code VARCHAR(20) DEFAULT NULL,
  change_date DATE DEFAULT NULL,
  change_desc VARCHAR(500) DEFAULT NULL,
  requested_by VARCHAR(100) DEFAULT NULL,
  reason TEXT DEFAULT NULL,
  impact_scope VARCHAR(255) DEFAULT NULL,
  impact_time VARCHAR(100) DEFAULT NULL,
  impact_cost VARCHAR(100) DEFAULT NULL,
  est_mandays DECIMAL(8,2) DEFAULT NULL,
  decision TINYINT NOT NULL DEFAULT 0,
  approver VARCHAR(100) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(100) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chg_pj (pj_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
